version: '3'

services:
  mdb-primary:
    image: 'bitnami/mongodb:4.0'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=somepassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey
      - MONGODB_ADVERTISED_HOSTNAME=mdb-primary

  mdb-secondary:
    image: 'bitnami/mongodb:4.0'
    depends_on:
      - mdb-primary
    environment:
      - MONGODB_PRIMARY_HOST=mdb-primary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_ROOT_PASSWORD=somepassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey
      - MONGODB_ADVERTISED_HOSTNAME=mdb-secondary

  mdb-arbiter:
    image: 'bitnami/mongodb:4.0'
    depends_on:
      - mdb-primary
    environment:
      - MONGODB_PRIMARY_HOST=mdb-primary
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_ROOT_PASSWORD=somepassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey
      - MONGODB_ADVERTISED_HOSTNAME=mdb-arbiter

  mongo-cli:
    image: 'bitnami/mongodb:latest'