
export enum ErrorType {
    NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
    BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
    UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
    FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
    CONFLICT_ERROR = 'CONFLICT_ERROR'
}