module.exports = {
    active_env: process.env.active_env,
    ui_url: process.env.ui_url,
    movies_db_key: process.env.movies_db_key,
    mongo_url: process.env.mongo_url,
    do_endpoint: process.env.do_endpoint,
    do_access_key_id: process.env.do_access_key_id,
    do_secret_access_key: process.env.do_secret_access_key,
    do_bucket: process.env.do_bucket,
    token_socket: process.env.token_socket,
    access_id: process.env.access_id,
    issuer: process.env.issuer,
    audience: process.env.audience,
    facebook_client_id: process.env.facebook_client_id,
    facebook_client_secret: process.env.facebook_client_secret,
    twitter_consumer_key: process.env.twitter_consumer_key,
    twitter_consumer_secret: process.env.twitter_consumer_secret,
    google_client_id: process.env.google_client_id,
    google_client_secret: process.env.google_client_secret
};